import type { DockerfileConfig, DockerfileFeatureToggle } from '@/config/config'

export const DOCKERFILE = 'Dockerfile'

// Apt packages that EVERY image must have — git for the agent runtime,
// curl/ca-certificates/gnupg for HTTPS and key fetches that downstream layers
// (e.g. the gh keyring) depend on. Listed first in the apt-get install line so
// the package set is self-documenting at a glance.
const BASELINE_APT_PACKAGES = ['git', 'ca-certificates', 'curl', 'gnupg'] as const

// curl-impersonate is the only currently-working way to query DuckDuckGo from
// a non-browser client on residential IPs in 2026. DDG fingerprints incoming
// requests at the TLS handshake (JA3/JA4) and HTTP/2 SETTINGS-frame layer
// before any HTTP headers are read; Bun's native fetch cannot match Chrome's
// fingerprint (upstream Bun issue #11368, open) so requests get gated behind
// 202 anomaly-modal responses, escalating to interactive duck-picker
// challenges. See `src/agent/tools/ddg.ts` for the runtime invocation.
//
// Pinned to lexiforest's actively-maintained fork (Chrome 136+ profiles in
// v1.5.6, May 2026), NOT the original `lwthiker/curl-impersonate` whose last
// release v0.6.1 (March 2024) carries Chrome ≤116 profiles — two years stale
// and useless against current DDG fingerprinting. Bumping: replace the
// version + sha256 constants below and run `typeclaw start --build` in any
// agent folder per the AGENTS.md "owns the Dockerfile" rule. Verify the new
// release ships the wrapper named in CURL_IMPERSONATE_PROFILE; lexiforest
// regenerates the bundled wrappers on Chrome major bumps and occasionally
// drops older ones.
export const CURL_IMPERSONATE_VERSION = 'v1.5.6'
export const CURL_IMPERSONATE_SHA256_AMD64 = 'b60344f63b9ed8806f0e9f7fd357d9f6c9a82aca279ed1e9e257d544885dcbde'
export const CURL_IMPERSONATE_SHA256_ARM64 = '6766bc67fd3e8e2313875f32b36b5a3fab02beffe77e5f1cf7fc5da99731d403'
// Wrapper symlink shipped in the v1.5.6 tarball. The tarball lays out
// curl_chrome136 → curl_chrome alongside the canonical `curl-impersonate`
// binary; we invoke the version-pinned wrapper so a future release that
// drops chrome136 fails loudly at search time instead of silently regressing
// the impersonation to whatever `curl_chrome` resolves to.
export const CURL_IMPERSONATE_PROFILE = 'chrome136'

// Shared-library runtime deps Chrome for Testing needs to launch on amd64
// Debian trixie (base of `oven/bun:1-slim`). `agent-browser install
// --with-deps` (v0.27.0) is supposed to install these but silently no-ops:
// its hardcoded list omits `libglib2.0-0t64`, so Chrome dies on launch
// with `libglib-2.0.so.0: cannot open shared object file` even though the
// binary download and `--with-deps` both exit 0. We install the full
// Playwright-tested chromium dep set here in Layer 2 so the bug doesn't
// recur if upstream omits another package; Layer 5 still calls
// `--with-deps` as a no-op-on-cache-hit backstop for future deps.
//
// Package list mirrors Playwright's `debian13-x64` chromium deps in
// nativeDeps.ts (https://github.com/microsoft/playwright). t64-suffixed
// names are the trixie-renamed variants from the 64-bit time_t ABI
// transition; SONAMEs (libglib-2.0.so.0 etc.) are unchanged. Packages
// without t64 here have no t64 sibling on trixie — verified against
// packages.debian.org/trixie. Fonts are intentionally omitted: the
// reported failure is launch-time linker errors, not rendering glyphs;
// font packages (esp. fonts-noto-cjk) cost ~50MB+ for no launch impact.
export const CHROME_RUNTIME_APT_PACKAGES_AMD64 = [
  'libasound2t64',
  'libatk-bridge2.0-0t64',
  'libatk1.0-0t64',
  'libatspi2.0-0t64',
  'libcairo2',
  'libcups2t64',
  'libdbus-1-3',
  'libdrm2',
  'libgbm1',
  'libglib2.0-0t64',
  'libnspr4',
  'libnss3',
  'libpango-1.0-0',
  'libx11-6',
  'libxcb1',
  'libxcomposite1',
  'libxdamage1',
  'libxext6',
  'libxfixes3',
  'libxkbcommon0',
  'libxrandr2',
] as const

type AptFeature = {
  toAptArgs: (toggle: DockerfileFeatureToggle) => string[]
}

const APT_FEATURES: Record<'ffmpeg' | 'gh' | 'tmux' | 'python', AptFeature> = {
  ffmpeg: { toAptArgs: (v) => singlePackageArgs('ffmpeg', v) },
  gh: { toAptArgs: (v) => singlePackageArgs('gh', v) },
  tmux: { toAptArgs: (v) => singlePackageArgs('tmux', v) },
  python: {
    toAptArgs: (v) => (v === true ? ['python3', 'python3-pip', 'python3-venv', 'python-is-python3'] : []),
  },
}

export function buildDockerfile(config: DockerfileConfig = defaultConfig()): string {
  const aptArgs = collectAptArgs(config)
  const ghKeyringLayer = renderGhKeyringLayer(config.gh)
  const customLines = renderCustomDockerfileLines(config.append)

  return `${BUILDKIT_HEADER}
# AUTOGENERATED by typeclaw — do not edit.
# This file is rewritten on every \`typeclaw start\` from src/init/dockerfile.ts
# in the typeclaw repo. Local edits will be overwritten (and committed away if
# the working tree is dirty). To change the template, edit dockerfile.ts there.

${FROM_AND_WORKDIR}

# Layers are ordered most-stable first to maximize Docker layer cache hits on
# rebuilds. Anything that pulls from npm (volatile) sits below anything that
# pulls from apt (stable, version-pinned by the base image's debian release),
# and the heavy Chrome-for-Testing download on amd64 is isolated in its own
# final layer so unrelated changes do not invalidate it.

${LAYER_0_APT_KEEP_CACHE}

${ghKeyringLayer}# Layer 2 (changes when the package list changes): the actual apt install.
# Cache mounts make a re-install nearly free when this layer is invalidated:
# .deb files come straight from the host's BuildKit cache instead of being
# refetched from Debian/GitHub mirrors. Package set is composed from the
# \`dockerfile\` config block in typeclaw.json — toggles for tmux/python/gh/
# ffmpeg fan out into the args below. Baseline (git/ca-certificates/curl/
# gnupg) is always installed because downstream layers depend on it.
#
# No \`rm -rf /var/lib/apt/lists/*\` because the lists live on a cache mount
# that is excluded from the image layer by definition.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    apt-get update \\
 && apt-get install -y --no-install-recommends \\
      ${aptArgs.join(' ')} \\
 && if [ "$TARGETARCH" = "arm64" ]; then \\
      apt-get install -y --no-install-recommends chromium; \\
    else \\
      apt-get install -y --no-install-recommends \\
        ${CHROME_RUNTIME_APT_PACKAGES_AMD64.join(' ')}; \\
    fi

${LAYER_2_5_CURL_IMPERSONATE}

${LAYER_3_AGENT_BROWSER_ARM64_CONFIG}

${LAYER_4_AGENT_BROWSER_INSTALL}

${LAYER_5_CHROME_FOR_TESTING}

# The agent folder (including node_modules) is bind-mounted at runtime by
# \`typeclaw start\`, so we do not COPY or install here. This keeps the image
# tiny and lets edits on the host take effect without rebuilds.

ENV NODE_ENV=production

# Pin agent-messenger's config dir into the agent's workspace/ so KakaoTalk
# (and any future agent-messenger-backed channel) reads/writes credentials
# inside the bind-mounted agent folder. Without this, the SDK would default
# to /root/.config/agent-messenger inside the container, which doesn't
# survive container restarts and isn't visible from the host. The agent
# folder's bind-mount maps /agent → host's agent dir, so the credentials
# end up at <agentDir>/workspace/.agent-messenger/ on the host.
ENV AGENT_MESSENGER_CONFIG_DIR=/agent/workspace/.agent-messenger

${customLines}ENTRYPOINT ["bun", "run", "typeclaw"]
CMD ["run"]
`
}

// Recipe for the prebuilt typeclaw-base image published to
// ghcr.io/typeclaw/typeclaw-base by .github/workflows/base-image.yml. Built
// from the same constants and layer templates as buildDockerfile() so the
// two cannot drift — the published image is a function of this source, not
// a checked-in Dockerfile that needs hand-syncing. The base intentionally
// stops before the per-agent layers (gh keyring, apt feature toggles,
// dockerfile.append, ENV, ENTRYPOINT) so users can still toggle them via
// typeclaw.json without forcing a base-image rebuild.
//
// Layer 2's apt-get install line installs only the baseline packages, NOT
// the gh/python/tmux/ffmpeg toggles — those layer onto the base in the
// per-agent Dockerfile.
export function buildBaseDockerfile(): string {
  return `${BUILDKIT_HEADER}
# AUTOGENERATED by scripts/emit-base-dockerfile.ts from src/init/dockerfile.ts.
# Do not edit by hand — your changes will be lost on the next CI run.

${FROM_AND_WORKDIR}

${LAYER_0_APT_KEEP_CACHE}

# Layer 2 (baseline only): apt baseline + Chrome runtime libs. Toggle-driven
# packages (gh/python/tmux/ffmpeg) are intentionally NOT installed here —
# they layer onto the base in the per-agent Dockerfile so users can opt in/
# out via typeclaw.json without forcing a base-image rebuild.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    apt-get update \\
 && apt-get install -y --no-install-recommends \\
      ${BASELINE_APT_PACKAGES.join(' ')} \\
 && if [ "$TARGETARCH" = "arm64" ]; then \\
      apt-get install -y --no-install-recommends chromium; \\
    else \\
      apt-get install -y --no-install-recommends \\
        ${CHROME_RUNTIME_APT_PACKAGES_AMD64.join(' ')}; \\
    fi

${LAYER_2_5_CURL_IMPERSONATE}

${LAYER_3_AGENT_BROWSER_ARM64_CONFIG}

${LAYER_4_AGENT_BROWSER_INSTALL}

${LAYER_5_CHROME_FOR_TESTING}
`
}

// Shared layer templates. Both buildDockerfile() (per-agent) and
// buildBaseDockerfile() (prebuilt base image) compose from these so the
// two outputs cannot drift on Chrome runtime libs, curl-impersonate
// version, or the agent-browser install path.

const BUILDKIT_HEADER = `# syntax=docker/dockerfile:1.7`

const FROM_AND_WORKDIR = `FROM oven/bun:1-slim

WORKDIR /agent

ARG TARGETARCH`

// Layer 0: defeat Debian's apt auto-clean so \`--mount=type=cache\` below
// actually retains downloaded .debs across builds. The default
// /etc/apt/apt.conf.d/docker-clean (inherited from debian:slim) deletes
// /var/cache/apt/archives at the end of every apt invocation, which would
// nullify our cache mount. Also pre-create the keyring dir so the gh repo
// layer in the per-agent Dockerfile is one cheap cp/echo with no mkdir.
const LAYER_0_APT_KEEP_CACHE = `# Layer 0 (rarely changes): defeat Debian's apt auto-clean so cache mounts
# below actually retain downloaded .debs across builds.
RUN rm -f /etc/apt/apt.conf.d/docker-clean \\
 && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \\
 && mkdir -p -m 755 /etc/apt/keyrings`

// Layer 2.5: install pinned curl-impersonate (lexiforest fork) for the
// websearch tool's DDG scraper. Required to evade DDG's TLS/HTTP2
// fingerprinting on residential IPs — see src/agent/tools/ddg.ts for the
// full rationale. Placed after Layer 2 so curl + ca-certificates + tar
// (already in baseline) are present, and before agent-browser so a version
// bump there doesn't invalidate this layer.
const LAYER_2_5_CURL_IMPERSONATE = `# Layer 2.5 (stable): pinned curl-impersonate (lexiforest fork) for DDG.
RUN ARCH_TARBALL="$(if [ "$TARGETARCH" = "arm64" ]; then echo aarch64-linux-gnu; else echo x86_64-linux-gnu; fi)" \\
 && ARCH_SHA="$(if [ "$TARGETARCH" = "arm64" ]; then echo ${CURL_IMPERSONATE_SHA256_ARM64}; else echo ${CURL_IMPERSONATE_SHA256_AMD64}; fi)" \\
 && cd /tmp \\
 && curl -fsSL -o curl-impersonate.tar.gz \\
      "https://github.com/lexiforest/curl-impersonate/releases/download/${CURL_IMPERSONATE_VERSION}/curl-impersonate-${CURL_IMPERSONATE_VERSION}.\${ARCH_TARBALL}.tar.gz" \\
 && echo "\${ARCH_SHA}  curl-impersonate.tar.gz" | sha256sum -c - \\
 && tar -xzf curl-impersonate.tar.gz -C /usr/local/bin/ \\
 && rm curl-impersonate.tar.gz \\
 && /usr/local/bin/curl_${CURL_IMPERSONATE_PROFILE} --version > /dev/null`

const LAYER_3_AGENT_BROWSER_ARM64_CONFIG = `# Layer 3 (stable, arm64 only): point agent-browser at the apt-installed
# chromium. Independent of the npm install below so it stays cached across
# agent-browser version bumps.
RUN if [ "$TARGETARCH" = "arm64" ]; then \\
      mkdir -p /root/.agent-browser \\
   && printf '%s\\n' '{"executablePath":"/usr/bin/chromium"}' > /root/.agent-browser/config.json; \\
    fi`

const LAYER_4_AGENT_BROWSER_INSTALL = `# Layer 4 (volatile): install agent-browser globally so it survives the
# runtime bind-mount over /agent/node_modules.
RUN --mount=type=cache,target=/root/.bun/install/cache,sharing=locked \\
    bun install -g agent-browser`

// Layer 5: download the pinned Chrome for Testing build into
// ~/.agent-browser/browsers/. NO cache mount on that path because the
// runtime needs the binary in the image. System shared libraries are
// already installed in Layer 2; --with-deps is a defense-in-depth backstop
// so a future agent-browser bump that adds new deps installs them
// automatically (near-no-op when Layer 2 already covers them).
const LAYER_5_CHROME_FOR_TESTING = `# Layer 5 (heavy, amd64 only): Chrome for Testing download.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    if [ "$TARGETARCH" != "arm64" ]; then \\
      agent-browser install --with-deps; \\
    fi`

function defaultConfig(): DockerfileConfig {
  return { ffmpeg: false, gh: true, python: true, tmux: true, append: [] }
}

function collectAptArgs(config: DockerfileConfig): string[] {
  const args: string[] = [...BASELINE_APT_PACKAGES]
  for (const key of ['ffmpeg', 'gh', 'python', 'tmux'] as const) {
    args.push(...APT_FEATURES[key].toAptArgs(config[key]))
  }
  return args
}

function singlePackageArgs(name: string, toggle: DockerfileFeatureToggle): string[] {
  if (toggle === false) return []
  if (toggle === true) return [name]
  return [`${name}=${toggle}`]
}

// The gh keyring bootstrap is a separate layer so editing the package list
// (the most frequent change) does not re-fetch the GPG key over the network.
// When `gh` is disabled, omit the layer entirely — both to skip the network
// roundtrip on cold builds and to keep the package source registry clean.
function renderGhKeyringLayer(toggle: DockerfileFeatureToggle): string {
  if (toggle === false) return ''
  return `# Layer 1 (rarely changes): register the GitHub CLI apt repository and trust
# its keyring. Split from the package install below so editing the package
# list (the most frequent change to this Dockerfile) does NOT re-fetch the
# GPG key over the network. The cache mount on /var/cache/apt covers the
# tiny gnupg/curl install we need to bootstrap the key fetch.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    apt-get update \\
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg \\
 && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \\
      | gpg --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
 && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \\
      > /etc/apt/sources.list.d/github-cli.list

`
}

function renderCustomDockerfileLines(lines: string[]): string {
  if (lines.length === 0) return ''
  return `# Custom lines from typeclaw.json#dockerfile.append.
${lines.join('\n')}

`
}
