export const DOCKERFILE = 'Dockerfile'

export function buildDockerfile(): string {
  return `# AUTOGENERATED by typeclaw — do not edit.
# This file is rewritten on every \`typeclaw start\` from src/init/dockerfile.ts
# in the typeclaw repo. Local edits will be overwritten (and committed away if
# the working tree is dirty). To change the template, edit dockerfile.ts there.

FROM oven/bun:1-slim

WORKDIR /agent

# Populated by buildkit. Used below to pick the right Chromium acquisition
# strategy for the build platform.
ARG TARGETARCH

# Layers are ordered most-stable first to maximize Docker layer cache hits on
# rebuilds. Anything that pulls from npm (volatile) sits below anything that
# pulls from apt (stable, version-pinned by the base image's debian release),
# and the heavy Chrome-for-Testing download on amd64 is isolated in its own
# final layer so unrelated changes do not invalidate it.

# Layer 1 (stable): all apt packages in a single update/install/cleanup cycle.
#   - git + ca-certificates: required by the agent runtime (cloning,
#     committing workspace state, version-controlled tooling).
#   - python3 + pip + venv + python-is-python3: agents routinely shell out to
#     Python scripts (data wrangling, ML tooling, ad-hoc \`pip install\`).
#     python-is-python3 makes \`python\` resolve to python3 so both names work.
#   - chromium (arm64 only): Chrome for Testing has no Linux ARM64 build, so
#     we use Debian's chromium package on that arch. Bundling it into the same
#     apt invocation avoids a second \`apt-get update\` later and keeps the
#     image's apt cache cleanup in one place.
RUN apt-get update \\
 && apt-get install -y --no-install-recommends \\
      git ca-certificates \\
      python3 python3-pip python3-venv python-is-python3 \\
 && if [ "$TARGETARCH" = "arm64" ]; then \\
      apt-get install -y --no-install-recommends chromium; \\
    fi \\
 && rm -rf /var/lib/apt/lists/*

# Layer 2 (stable, arm64 only): point agent-browser at the apt-installed
# chromium via its global config (~/.agent-browser/config.json — lowest-
# priority layer that env vars and CLI flags can still override). Independent
# of the npm install below, so it stays cached across agent-browser version
# bumps.
RUN if [ "$TARGETARCH" = "arm64" ]; then \\
      mkdir -p /root/.agent-browser \\
   && printf '%s\\n' '{"executablePath":"/usr/bin/chromium"}' > /root/.agent-browser/config.json; \\
    fi

# Layer 3 (volatile): install the agent-browser CLI globally so it survives
# the runtime bind-mount that overlays node_modules at /agent/node_modules.
# Isolated from the heavy Chrome download below so an npm-only version bump
# only re-runs this small layer (on amd64 the next layer still re-runs, but
# on arm64 nothing else has to).
RUN bun install -g agent-browser

# Layer 4 (heavy, amd64 only): download the pinned Chrome for Testing build
# into ~/.cache/agent-browser and apt-install the libs it needs. Kept last so
# it benefits from every layer above being cached, and so changes to git or
# the apt base don't invalidate hundreds of MB of Chrome state.
RUN if [ "$TARGETARCH" != "arm64" ]; then \\
      agent-browser install --with-deps; \\
    fi

# The agent folder (including node_modules) is bind-mounted at runtime by
# \`typeclaw start\`, so we do not COPY or install here. This keeps the image
# tiny and lets edits on the host take effect without rebuilds.

ENV NODE_ENV=production

ENTRYPOINT ["bun", "run", "typeclaw"]
CMD ["run"]
`
}
