import type { DockerfileConfig, DockerfileFeatureToggle } from '@/config/config'

export const DOCKERFILE = 'Dockerfile'

// Apt packages that EVERY image must have — git for the agent runtime,
// curl/ca-certificates/gnupg for HTTPS and key fetches that downstream layers
// (e.g. the gh keyring) depend on. Listed first in the apt-get install line so
// the package set is self-documenting at a glance.
const BASELINE_APT_PACKAGES = ['git', 'ca-certificates', 'curl', 'gnupg'] as const

type AptFeature = {
  toAptArgs: (toggle: DockerfileFeatureToggle) => string[]
}

const APT_FEATURES: Record<'ffmpeg' | 'gh' | 'tmux' | 'python', AptFeature> = {
  ffmpeg: { toAptArgs: (v) => singlePackageArgs('ffmpeg', v) },
  gh: { toAptArgs: (v) => singlePackageArgs('gh', v) },
  tmux: { toAptArgs: (v) => singlePackageArgs('tmux', v) },
  python: {
    toAptArgs: (v) => (v === true ? ['python3', 'python3-pip', 'python3-venv', 'python-is-python3'] : []),
  },
}

export function buildDockerfile(config: DockerfileConfig = defaultConfig()): string {
  const aptArgs = collectAptArgs(config)
  const ghKeyringLayer = renderGhKeyringLayer(config.gh)
  const customLines = renderCustomDockerfileLines(config.append)

  return `# syntax=docker/dockerfile:1.7
# AUTOGENERATED by typeclaw — do not edit.
# This file is rewritten on every \`typeclaw start\` from src/init/dockerfile.ts
# in the typeclaw repo. Local edits will be overwritten (and committed away if
# the working tree is dirty). To change the template, edit dockerfile.ts there.
#
# Cache strategy: \`# syntax=docker/dockerfile:1.7\` opts in to BuildKit, which
# enables \`--mount=type=cache\` below. Cache mounts persist across builds on
# the host's BuildKit instance but are NOT baked into the image — perfect for
# package manager caches (.deb files, bun's tarball cache) where we want
# fast rebuilds without bloating the runtime image. Cache mounts are
# explicitly NOT used for tool output that the runtime needs (e.g. the
# Chrome for Testing binary at \`~/.cache/agent-browser\`); those go through
# normal layers so they ship with the image.

FROM oven/bun:1-slim

WORKDIR /agent

# Populated by buildkit. Used below to pick the right Chromium acquisition
# strategy for the build platform.
ARG TARGETARCH

# Layers are ordered most-stable first to maximize Docker layer cache hits on
# rebuilds. Anything that pulls from npm (volatile) sits below anything that
# pulls from apt (stable, version-pinned by the base image's debian release),
# and the heavy Chrome-for-Testing download on amd64 is isolated in its own
# final layer so unrelated changes do not invalidate it.

# Layer 0 (rarely changes): defeat Debian's apt auto-clean so \`--mount=type=
# cache\` below actually retains downloaded .debs across builds. The default
# \`/etc/apt/apt.conf.d/docker-clean\` (inherited from debian:slim) deletes
# /var/cache/apt/archives at the end of every apt invocation, which would
# nullify our cache mount. Also pre-create the keyring dir so the gh repo
# layer below is one cheap cp/echo with no mkdir.
RUN rm -f /etc/apt/apt.conf.d/docker-clean \\
 && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \\
 && mkdir -p -m 755 /etc/apt/keyrings

${ghKeyringLayer}# Layer 2 (changes when the package list changes): the actual apt install.
# Cache mounts make a re-install nearly free when this layer is invalidated:
# .deb files come straight from the host's BuildKit cache instead of being
# refetched from Debian/GitHub mirrors. Package set is composed from the
# \`dockerfile\` config block in typeclaw.json — toggles for tmux/python/gh/
# ffmpeg fan out into the args below. Baseline (git/ca-certificates/curl/
# gnupg) is always installed because downstream layers depend on it.
#
# No \`rm -rf /var/lib/apt/lists/*\` because the lists live on a cache mount
# that is excluded from the image layer by definition.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    apt-get update \\
 && apt-get install -y --no-install-recommends \\
      ${aptArgs.join(' ')} \\
 && if [ "$TARGETARCH" = "arm64" ]; then \\
      apt-get install -y --no-install-recommends chromium; \\
    fi

# Layer 3 (stable, arm64 only): point agent-browser at the apt-installed
# chromium via its global config (~/.agent-browser/config.json — lowest-
# priority layer that env vars and CLI flags can still override). Independent
# of the npm install below, so it stays cached across agent-browser version
# bumps.
RUN if [ "$TARGETARCH" = "arm64" ]; then \\
      mkdir -p /root/.agent-browser \\
   && printf '%s\\n' '{"executablePath":"/usr/bin/chromium"}' > /root/.agent-browser/config.json; \\
    fi

# Layer 4 (volatile): install the agent-browser CLI globally so it survives
# the runtime bind-mount that overlays node_modules at /agent/node_modules.
# Cache mount on bun's tarball cache so an agent-browser version bump only
# re-fetches the changed package, not its entire dependency tree.
RUN --mount=type=cache,target=/root/.bun/install/cache,sharing=locked \\
    bun install -g agent-browser

# Layer 5 (heavy, amd64 only): download the pinned Chrome for Testing build
# into ~/.cache/agent-browser and apt-install the libs it needs. NO cache
# mount on ~/.cache/agent-browser: the runtime needs the binary in the
# image, and cache mounts are excluded from the final image. The apt-cache
# mounts ARE used for the --with-deps system libs install.
# Kept last so it benefits from every layer above being cached, and so
# changes to git or the apt base don't invalidate hundreds of MB of Chrome
# state.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    if [ "$TARGETARCH" != "arm64" ]; then \\
      agent-browser install --with-deps; \\
    fi

# The agent folder (including node_modules) is bind-mounted at runtime by
# \`typeclaw start\`, so we do not COPY or install here. This keeps the image
# tiny and lets edits on the host take effect without rebuilds.

ENV NODE_ENV=production

${customLines}ENTRYPOINT ["bun", "run", "typeclaw"]
CMD ["run"]
`
}

function defaultConfig(): DockerfileConfig {
  return { ffmpeg: false, gh: true, python: true, tmux: true, append: [] }
}

function collectAptArgs(config: DockerfileConfig): string[] {
  const args: string[] = [...BASELINE_APT_PACKAGES]
  for (const key of ['ffmpeg', 'gh', 'python', 'tmux'] as const) {
    args.push(...APT_FEATURES[key].toAptArgs(config[key]))
  }
  return args
}

function singlePackageArgs(name: string, toggle: DockerfileFeatureToggle): string[] {
  if (toggle === false) return []
  if (toggle === true) return [name]
  return [`${name}=${toggle}`]
}

// The gh keyring bootstrap is a separate layer so editing the package list
// (the most frequent change) does not re-fetch the GPG key over the network.
// When `gh` is disabled, omit the layer entirely — both to skip the network
// roundtrip on cold builds and to keep the package source registry clean.
function renderGhKeyringLayer(toggle: DockerfileFeatureToggle): string {
  if (toggle === false) return ''
  return `# Layer 1 (rarely changes): register the GitHub CLI apt repository and trust
# its keyring. Split from the package install below so editing the package
# list (the most frequent change to this Dockerfile) does NOT re-fetch the
# GPG key over the network. The cache mount on /var/cache/apt covers the
# tiny gnupg/curl install we need to bootstrap the key fetch.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \\
    apt-get update \\
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg \\
 && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \\
      | gpg --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
 && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \\
      > /etc/apt/sources.list.d/github-cli.list

`
}

function renderCustomDockerfileLines(lines: string[]): string {
  if (lines.length === 0) return ''
  return `# Custom lines from typeclaw.json#dockerfile.append.
${lines.join('\n')}

`
}
